import React from "react";
import "./Privacy_Policy.css";
import Navbar from "../../../components/Navbar/Navbar";
import Footer from "../../../components/Footer/Footer";
import Wrapper from "../../../components/Wrapper/Wrapper";

const Privacy_Policy = () => {
  return (
    <>
      <Navbar />
      <div className="privacy_policy">
        <Wrapper>
          <div className="privacy_policy_wrapper">
            <div className="privacy_policy_header">
              <h1>Privacy Policy</h1>
              <p>Last updated: May 2, 2024</p>
              <p>
                This Privacy Policy describes Our policies and procedures on the
                collection, use and disclosure of Your information when You use
                the Service and tells You about Your privacy rights and how the
                law protects You.
              </p>
              <p>
                We use Your Personal data to provide and improve the Service. By
                using the Service, You agree to the collection and use of
                information in accordance with this Privacy Policy.{" "}
              </p>
              <div className="definition">
                <h2>Interpretation and Definitions </h2>
                <h3>Interpretation</h3>
                <p>
                  {" "}
                  The words of which the initial letter is capitalized have
                  meanings defined under the following conditions. The following
                  definitions shall have the same meaning regardless of whether
                  they appear in singular or in plural.
                </p>
                <h3>Definitions</h3>{" "}
                <p> For the purposes of this Privacy Policy:</p>
                <p>
                  <span>Account</span> means a unique account created for You to
                  access our Service or parts of our Service.
                </p>
                <p>
                  <span>Affiliate</span> means an entity that controls, is
                  controlled by or is under common control with a party, where
                  "control" means ownership of 50% or more of the shares, equity
                  interest or other securities entitled to vote for election of
                  directors or other managing authority.
                </p>
                <p>
                  <span>Application</span> refers to SD Campus, the software
                  program provided by the Company.
                </p>
                <p>
                  {" "}
                  <span>Company</span> (referred to as either "the Company",
                  "We", "Us" or "Our" in this Agreement) refers to SD Campus,
                  Plot No-16, Block 7, Sector 5, Rajendra Nagar, Ghaziabad,
                  Uttar Pradesh 201005.
                </p>
                <p>
                  <span>Country</span> refers to: Uttar Pradesh, India
                </p>
                <p>
                  <span>Device</span> means any device that can access the
                  Service such as a computer, a cellphone or a digital tablet.
                </p>
                <p>
                  <span>Personal</span> Data is any information that relates to
                  an identified or identifiable individual.
                </p>
                <p>
                  {" "}
                  <span>Service</span> refers to the Application.
                </p>
                <p>
                  <span>Service</span> Provider means any natural or legal
                  person who processes the data on behalf of the Company. It
                  refers to third-party companies or individuals employed by the
                  Company to facilitate the Service, to provide the Service on
                  behalf of the Company, to perform services related to the
                  Service or to assist the Company in analyzing how the Service
                  is used.
                </p>
                <p>
                  {" "}
                  <span>Usage Data</span> refers to data collected
                  automatically, either generated by the use of the Service or
                  from the Service infrastructure itself (for example, the
                  duration of a page visit).
                </p>
                <p>
                  <span>You</span> means the individual accessing or using the
                  Service, or the company, or other legal entity on behalf of
                  which such individual is accessing or using the Service, as
                  applicable.
                </p>
              </div>
              <div className="personal_data">
                <h2>Collecting and Using Your Personal Data</h2>
                <h3>Types of Data Collected</h3>
                <h4> Personal Data</h4>
                <p>
                  We collect certain information about You to help us serve You better. The information collected by Us is of the following nature:
                </p>
                <p>
                  <ul>
                    <li>1. Name</li>
                    <li>2. Telephone Number</li>
                    <li>3. Email Address</li>
                    <li>4. Service Address</li>
                    <li>5. Other information about the service address which You give Us</li>
                    <li>6. Information about your device</li>
                    <li>7. Your IP address</li>
                    <li>8. Network information</li>
                    <li>9. User uploaded photo</li>
                    <li>10. Demographic information such as postcode, preferences and interests</li>
                    <li>11. Any other personal information which you give us in connection while booking a service or is relevant to customer surveys and/or offers.</li>
                  </ul>
                </p>

                <h4>Usage Data</h4>
                <p>
                  Usage Data is collected automatically when using the Service.
                </p>{" "}
                <p>
                  {" "}
                  Usage Data may include information such as Your Device's
                  Internet Protocol address (e.g. IP address), browser type,
                  browser version, the pages of our Service that You visit, the
                  time and date of Your visit, the time spent on those pages,
                  unique device identifiers and other diagnostic data.
                </p>
                <p>
                  When You access the Service by or through a mobile device, We
                  may collect certain information automatically, including, but
                  not limited to, the type of mobile device You use, Your mobile
                  device unique ID, the IP address of Your mobile device, Your
                  mobile operating system, the type of mobile Internet browser
                  You use, unique device identifiers and other diagnostic data.
                </p>
                <p>
                  {" "}
                  We may also collect information that Your browser sends
                  whenever You visit our Service or when You access the Service
                  by or through a mobile device.
                </p>
                <h4>Information Collected while Using the Application</h4>
                <p>
                  {" "}
                  While using Our Application, in order to provide features of
                  Our Application, We may collect, with Your prior permission:
                </p>
                <p> Information regarding your location </p>
                <p>
                  {" "}
                  We use this information to provide features of Our Service, to
                  improve and customize Our Service. The information may be
                  uploaded to the Company's servers and/or a Service Provider's
                  server or it may be simply stored on Your device.
                </p>
                <p>
                  {" "}
                  You can enable or disable access to this information at any
                  time, through Your Device settings.
                </p>
                <h3>Use of Your Personal Data</h3>
                <p>
                  The Company may use Personal Data for the following purposes:
                </p>
                <p>
                  <span>To provide and maintain our Service</span>
                  including to monitor the usage of our Service.
                </p>{" "}
                <p>
                  {" "}
                  <span>To manage Your Account:</span> to manage Your
                  registration as a user of the Service. The Personal Data You
                  provide can give You access to different functionalities of
                  the Service that are available to You as a registered user.
                </p>
                <p>
                  {" "}
                  <span>For the performance of a contract:</span> the
                  development, compliance and undertaking of the purchase
                  contract for the products, items or services You have
                  purchased or of any other contract with Us through the
                  Service.
                </p>
                <p>
                  <span>To contact You:</span>
                  To contact You by email, telephone calls, SMS, or other
                  equivalent forms of electronic communication, such as a mobile
                  application's push notifications regarding updates or
                  informative communications related to the functionalities,
                  products or contracted services, including the security
                  updates, when necessary or reasonable for their
                  implementation.
                </p>
                <p>
                  <span>To provide You</span> with news, special offers and
                  general information about other goods, services and events
                  which we offer that are similar to those that you have already
                  purchased or enquired about unless You have opted not to
                  receive such information.
                </p>
                <p>
                  <span>To manage Your requests:</span> To attend and manage
                  Your requests to Us.
                </p>
                <p>
                  {" "}
                  <span>For business transfers:</span> We may use Your
                  information to evaluate or conduct a merger, divestiture,
                  restructuring, reorganization, dissolution, or other sale or
                  transfer of some or all of Our assets, whether as a going
                  concern or as part of bankruptcy, liquidation, or similar
                  proceeding, in which Personal Data held by Us about our
                  Service users is among the assets transferred.
                </p>
                <p>
                  <span>For other purposes:</span> We may use Your information
                  for other purposes, such as data analysis, identifying usage
                  trends, determining the effectiveness of our promotional
                  campaigns and to evaluate and improve our Service, products,
                  services, marketing and your experience.
                </p>
                <p>
                  {" "}
                  We may share Your personal information in the following
                  situations:
                </p>
                <p>
                  • <span> With Service Providers:</span>
                  We may share Your personal information with Service Providers
                  to monitor and analyze the use of our Service, to contact You.
                </p>
                <p>
                  <span> For business transfers:</span>
                  We may share or transfer Your personal information in
                  connection with, or during negotiations of, any merger, sale
                  of Company assets, financing, or acquisition of all or a
                  portion of Our business to another company.
                </p>
                <p>
                  <span> With Affiliates:</span>We may share Your information
                  with Our affiliates, in which case we will require those
                  affiliates to honor this Privacy Policy. Affiliates include
                  Our parent company and any other subsidiaries, joint venture
                  partners or other companies that We control or that are under
                  common control with Us.
                </p>
                <p>
                  <span>With business partners:</span> We may share Your
                  information with Our business partners to offer You certain
                  products, services or promotions.
                </p>
                <p>
                  <span>With other users:</span> when You share personal
                  information or otherwise interact in the public areas with
                  other users, such information may be viewed by all users and
                  may be publicly distributed outside.
                </p>
                <p>
                  •<span> With Your consent:</span> We may disclose Your
                  personal information for any other purpose with Your consent.
                </p>
                <h3>Retention of Your Personal Data</h3>
                <p>
                  The Company will retain Your Personal Data only for as long as
                  is necessary for the purposes set out in this Privacy Policy.
                  We will retain and use Your Personal Data to the extent
                  necessary to comply with our legal obligations (for example,
                  if we are required to retain your data to comply with
                  applicable laws), resolve disputes, and enforce our legal
                  agreements and policies.
                </p>{" "}
                <p>
                  The Company will also retain Usage Data for internal analysis
                  purposes. Usage Data is generally retained for a shorter
                  period of time, except when this data is used to strengthen
                  the security or to improve the functionality of Our Service,
                  or We are legally obligated to retain this data for longer
                  time periods.
                </p>
                <h3> Transfer of Your Personal Data</h3>
                <p>
                  Your information, including Personal Data, is processed at the
                  Company's operating offices and in any other places where the
                  parties involved in the processing are located. It means that
                  this information may be transferred to — and maintained on —
                  computers located outside of Your state, province, country or
                  other governmental jurisdiction where the data protection laws
                  may differ than those from Your jurisdiction.
                </p>
                <p>
                  {" "}
                  Your consent to this Privacy Policy followed by Your
                  submission of such information represents Your agreement to
                  that transfer.
                </p>
                <p>
                  {" "}
                  The Company will take all steps reasonably necessary to ensure
                  that Your data is treated securely and in accordance with this
                  Privacy Policy and no transfer of Your Personal Data will take
                  place to an organization or a country unless there are
                  adequate controls in place including the security of Your data
                  and other personal information.
                </p>
                <h3>Delete Your Personal Data</h3>
                <p>
                  You have the right to delete or request that We assist in
                  deleting the Personal Data that We have collected about You.
                </p>
                <p>
                  Our Service may give You the ability to delete certain
                  information about You from within the Service.
                </p>
                <p>
                  {" "}
                  You may update, amend, or delete Your information at any time
                  by signing in to Your Account, if you have one, and visiting
                  the account settings section that allows you to manage Your
                  personal information. You may also contact Us to request
                  access to, correct, or delete any personal information that
                  You have provided to Us.
                </p>
                <p>
                  Please note, however, that We may need to retain certain
                  information when we have a legal obligation or lawful basis to
                  do so.{" "}
                </p>
                <h3> Disclosure of Your Personal Data</h3>
                <h4> Business Transactions</h4>
                <p>
                  {" "}
                  If the Company is involved in a merger, acquisition or asset
                  sale, Your Personal Data may be transferred. We will provide
                  notice before Your Personal Data is transferred and becomes
                  subject to a different Privacy Policy.
                </p>
                <h4>Law enforcement</h4>
                <p>
                  Under certain circumstances, the Company may be required to
                  disclose Your Personal Data if required to do so by law or in
                  response to valid requests by public authorities (e.g. a court
                  or a government agency).
                </p>
                <h4>Other legal requirements</h4>
                <p>
                  {" "}
                  The Company may disclose Your Personal Data in the good faith
                  belief that such action is necessary to:
                </p>
                <p>
                  • <span> Comply with a legal obligation</span>
                </p>
                <p>
                  •{" "}
                  <span>
                    {" "}
                    Protect and defend the rights or property of the Company
                  </span>
                </p>
                <p>
                  •{" "}
                  <span>
                    {" "}
                    Prevent or investigate possible wrongdoing in connection
                    with the Service
                  </span>
                </p>
                <p>
                  •{" "}
                  <span>
                    {" "}
                    Protect the personal safety of Users of the Service or the
                    public
                  </span>
                </p>
                <p>
                  • <span> Protect against legal liability</span>
                </p>
                <h3>Security of Your Personal Data</h3>
                <p>
                  The security of Your Personal Data is important to Us, but
                  remember that no method of transmission over the Internet, or
                  method of electronic storage is 100% secure. While We strive
                  to use commercially acceptable means to protect Your Personal
                  Data, We cannot guarantee its absolute security.
                </p>
              </div>

              <div className="children_policy">
                <h2>Children's Privacy </h2>
                <p>
                  {" "}
                  To register on the website/app, you must meet the Age Requirements specified hereinbelow. If you are a ‘Minor’ or ‘Child’, i.e., an individual who does not meet the Age Requirements, then you may not register on the website/app, and only your parent can register on your behalf, agree to all website/app Terms and
                  Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.
                  app does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website/app, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.
                  If you are a parent / legal guardian and you are aware that your child has provided us with personal information without your consent, please contact us at info@sdempire.co.in

                  If your Child faces bullying, abuse or harassment while availing our Services, please contact us at info@sdempire.co.in
                </p>
                <p>
                  If We need to rely on consent as a legal basis for processing
                  Your information and Your country requires consent from a
                  parent, We may require Your parent's consent before We collect
                  and use that information.
                </p>
              </div>

              <div className="links">
                <h2> Links to Other Websites </h2>
                <p>
                  Our Service may contain links to other websites that are not
                  operated by Us. If You click on a third party link, You will
                  be directed to that third party's site. We strongly advise You
                  to review the Privacy Policy of every site You visit.
                </p>
                <p>
                  We have no control over and assume no responsibility for the
                  content, privacy policies or practices of any third party
                  sites or services.
                </p>
              </div>
              <div className="dnd">
                <h2>DND (Do Not Disturb) / NDNC (National Do Not Call)</h2>
                <p>
                  By using the Website and/or registering yourself at sdcampus.com you authorize us to contact you via email or phone call or sms and offer you our services, imparting product knowledge, offer promotional offers running on website & offers offered by the associated third parties, for which reasons, personally identifiable information may be collected. And irrespective of the fact if you have also registered yourself under DND or DNC or NCPR service, you still authorize us to give you a call from sdcampus.com for the above mentioned purposes till 365 days of your registration with us.</p>
              </div>
              <div className="refund_policy">
                <h2>Refund Policy</h2>
                <p>At SD Campus, we want our customers to be fully satisfied with their purchases. However, we do have a no refund policy for most products and services.</p>

                <p><strong>Online Batches and Other Services</strong></p>
                <p> All online batches, coaching services, and other intangible products are non-refundable after purchase. We do not provide refunds on these services.</p>
                <p><strong>Physical Products</strong></p>
                <p> Physical products like books and accessories are eligible for refund or replacement only if:</p>
                <ul>
                  <li>The item received is damaged or defective. A replacement will be provided.</li>
                  <li>The item is lost by the courier partner during transit. A replacement or refund will be provided.</li>
                  <li> If you receive a wrong or damaged product, please contact our customer support team within 7 days along with order details and images. We will evaluate and provide a resolution.</li>
                </ul>
                <p><strong>Incorrect Purchases</strong></p>
                <p> If you purchase a product or batch by mistake, you can request to change it to another batch or product of the same value. This change request must be made within 10 days of the original purchase.</p>
                <p><strong>Changes/Cancellations</strong></p>
                <p> We do not provide refunds if you change your mind or wish to cancel an order after purchase. Please review products carefully before ordering.</p>
                <p>We hope this refund policy provides clarity to our customers. Please reach out with any other questions. We aim to resolve any issues to your satisfaction.</p>
              </div>

              <div className="changes">
                <h2>Changes to this Privacy Policy</h2>
                <p>
                  We may update Our Privacy Policy from time to time. We will
                  notify You of any changes by posting the new Privacy Policy on
                  this page.
                </p>
                <p>
                  We will let You know via email and/or a prominent notice on
                  Our Service, prior to the change becoming effective and update
                  the "Last updated" date at the top of this Privacy Policy.
                </p>
                <p>
                  {" "}
                  You are advised to review this Privacy Policy periodically for
                  any changes. Changes to this Privacy Policy are effective when
                  they are posted on this page.
                </p>
              </div>

              <div className="contact_us">
                <h3> Contact Us</h3>
                <p>
                  If you have any questions about this Privacy Policy, You can
                  contact us:
                </p>
                <p>By email: <a href="mailto:contact@sdempire.co.in">contact@sdempire.co.in</a></p>
                <p>
                  By visiting this page on our website:
                  <a href="https://www.sdcampus.com/"> https://www.sdcampus.com/</a>
                </p>
                <p>By phone number: <a href="tel:+917428394519">+917428394519</a></p>
              </div>
            </div>
          </div>
        </Wrapper>
      </div>
      <Footer />
    </>
  );
};

export default Privacy_Policy;
